### ISSUE TITLE
Front page highlights displaying incorrectly.

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/vassallandcoldharbour#18]
Logged on as admin

I published three news items. Added them to the highlights. They do not display correctly:

![image](https://cloud.githubusercontent.com/assets/6060985/7706462/7e732670-fe42-11e4-887e-5ad2792489e1.png)

@pmackay  @djwesto Can we also set up labels etc for this area for reporting bugs and feature requests etc. Should we have some milestones as well?

**Comment by djwesto** [comment]
Thanks for that @GilesGibson – that looks like it's the carousel which is actually appearing at the top of the view but hadn't been exposed because of the fact we didn't feature any content.

**Comment by djwesto** [comment]
Closing now – please see my response to Issue #20 which relates to the same matter.
