### ISSUE TITLE
News items - repeat displays of links?

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/vassallandcoldharbour#19]
Live Vassall site. Logged on as admin.

http://www.vassallandcoldharbour.org.uk/news/loughborough-road-urban-food-growing

The news item had duplicate items listed in bottom right hand side

![image](https://cloud.githubusercontent.com/assets/6060985/7710113/9932fc62-fe59-11e4-9e3a-a46c8ebca31c.png)

It doesn't say what the items listed  are - tags? categories? Also duplicates tow of them. may be a valid reason but without explanation for the user it is confusing.

**Comment by pmackay** [comment]
I think this is resolved having got rid of duplicates.
