### ISSUE TITLE
Fix text wrapping in news listings

### ISSUE THREAD

**Issue by djwesto** [folklabs/vassallandcoldharbour#21]
As on Herne Hill, we're still seeing this accursed issue with the Comments field wrapping underneath images on news listings. How can I fix this?

![screenshot 2015-05-27 12 41 53](https://cloud.githubusercontent.com/assets/702685/7841930/cccbc33a-0497-11e5-9204-7f7b8dd9f2a9.png)

I've searched high and low on the [Views settings for the List News Articles view](http://dev-vassallandcoldharbour:8888/admin/structure/views/view/openlocal_news/edit/list_news_articles) to try to find where I can wrap the objects outside the image in a separate div or other element, but I can't find it anywhere... Can you help guide me, @pmackay? I'd really like to put this one to bed once and for all.

**Comment by pmackay** [comment]
Done
