### ISSUE TITLE
Links in alerts are not visible

### ISSUE THREAD

**Issue by pmackay** [folklabs/vassallandcoldharbour#25]
![screen shot 2015-06-10 at 14 12 50](https://cloud.githubusercontent.com/assets/115115/8083206/d8e64b34-0f7a-11e5-9bc3-1a595b718a2a.png)

**Comment by djwesto** [comment]
Now fixed with better styles for alert box links:

![image](https://cloud.githubusercontent.com/assets/702685/8131470/6186f932-1112-11e5-969e-b1961b92c597.png)
