### ISSUE TITLE
Fix button corner styling to be consistent

### ISSUE THREAD

**Issue by pmackay** [folklabs/vassallandcoldharbour#28]
![screen shot 2015-06-11 at 14 16 13](https://cloud.githubusercontent.com/assets/115115/8107858/70cbc928-1044-11e5-94f4-2b0c7779107f.png)

**Comment by djwesto** [comment]
Fixed with a global button extend definition.

![image](https://cloud.githubusercontent.com/assets/702685/8131063/a90f2872-110f-11e5-8265-48941cc2a1a6.png)

Closing but shout if you see any which are still wrong.
