### ISSUE TITLE
Homepage carousel headline text needs fixes for spacing and positioning

### ISSUE THREAD

**Issue by djwesto** [folklabs/vassallandcoldharbour#29]
### Line spacing

Line spacing between each line of the heading text should ideally be reduced to the point where the lines are either close or touching:
![image](https://cloud.githubusercontent.com/assets/702685/8541311/12814f78-2485-11e5-8eb4-d1cb1a617a83.png)
### Positioning

Positioning needs to be fixed on all platforms / browsers (possibly one for @pmackay). We're seeing issues on Chrome and possibly other Mac browsers. Also need to test on Windows. It's hard to determine what's causing the problem:

![image](https://cloud.githubusercontent.com/assets/702685/8541344/50bb1af8-2485-11e5-84df-38f223531c7e.png)

**Comment by djwesto** [comment]
I have a suspicion the repositioning may be caused by absolute and relative positioning bugs brought over from Herne Hill...

**Comment by pmackay** [comment]
What browser are you using? I'm seeing this on FF and Chrome now:

![screen shot 2015-07-07 at 09 56 11](https://cloud.githubusercontent.com/assets/115115/8542575/96ae6386-248e-11e5-9d12-efd3d1e834a1.png)

**Comment by pmackay** [comment]
Also just pushed fix for height issue on Chrome which seems better.

**Comment by pmackay** [comment]
Cannot see these issues anymore.
