### ISSUE TITLE
News teaser cards – user avatar image is not aligned next to user name

### ISSUE THREAD

**Issue by djwesto** [folklabs/vassallandcoldharbour#3]
I need to work out how to get the user's avatar image to appear next to their name – at the moment, it flops down below:

![image](https://cloud.githubusercontent.com/assets/702685/7374953/32cb79dc-edcd-11e4-90b4-bb0a6a5c92a8.png)

**Comment by pmackay** [comment]
I just fixed this for homepage news. If it seems ok, I can update the news
page too.

**Comment by djwesto** [comment]
Great! Thanks.
