### ISSUE TITLE
web site crash - when creating new content

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/vassallandcoldharbour#30]
logged on as giles.

Tried to edit the entry for http://www.vassallandcoldharbour.org.uk/organisations/myatts-fields-park-project

got this:

![image](https://cloud.githubusercontent.com/assets/6060985/8548223/66d43dd4-24bb-11e5-9e62-36cbca09930b.png)

@pmackay need to fix if poss.

**Comment by GilesGibson** [comment]
On a similar note - I cannot create an organisation, get the same error message. @pmackay

**Comment by pmackay** [comment]
I think was a simple change of PHP version, please try again and note
anything else that behaves strangely.

**Comment by pmackay** [comment]
Not heard anything so closing, re-open if happens again.
