### ISSUE TITLE
Fix footer text

### ISSUE THREAD

**Issue by pmackay** [folklabs/vassallandcoldharbour#4]

**Comment by djwesto** [comment]
When you say "fix" the footer text, I assume you mean change the formatting of the hyperlinks so they're more visible against the green background, etc?

I'd like to do that but also, at some point, we could do with updating the formatting of the footer to add more content in there – specifically, the legally required content for non-profits etc.

**Comment by pmackay** [comment]
Actually meant the content, edit the copyright notice, etc.
