### ISSUE TITLE
News item - how to provide a downloadable file

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/vassallandcoldharbour#42]
VAC site. Logged on as gilesgibson. 

I wanted to create a news item and provide a hyperlink that would allow a ppt file to be downloaded when users click on it. The link dialogue box doesn't have that option as far as I can see. How would a user do this @pmackay ?

**Comment by pmackay** [comment]
Wouldnt you need to upload a PPT file first? Was that possible?

**Comment by GilesGibson** [comment]
yes, couldn't see where in the dialogue box it allowed you to do that. Different to the HH one I think.

**Comment by GilesGibson** [comment]
just checked HH one, I was wrong, nowhere on that link that can do it either. Getting confused, we used to be able to do this quite easily.

**Comment by pmackay** [comment]
Will be handled in future upgrade when https://github.com/folklabs/openlocal/issues/20 is implemented.
