### ISSUE TITLE
How to edit content on home page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/vassallandcoldharbour#43]
Logged on as Giles Gibson.

How can the site admin change the text on the home page where it describes the mission statement? Tori wants to change the text a little.

**Comment by pmackay** [comment]
Have tweaked permissions for site managers. Should now see the "Customise this page" button at bottom of homepage. Cick and then click the cog button in top left of content box for mission statement.

**Comment by GilesGibson** [comment]
I get the pop-up saying that it is being locked by Victoria Sherwin.... has been for 30 mins plus. However, it also says at the bottom that she is not logged on. I assume I just force the break and continue to edit.

**Comment by GilesGibson** [comment]
Have just gone ahead and edited it. Seems OK.

**Comment by GilesGibson** [comment]
@pmackay Just tried editing it again - unable to as no cog symbol visible:

![image](https://cloud.githubusercontent.com/assets/6060985/12233439/4568303c-b85f-11e5-967a-acea7cb48549.png)

**Comment by pmackay** [comment]
Have tweaked permissions, please try again.

**Comment by GilesGibson** [comment]
Ta, worked this time.
