### ISSUE TITLE
Opening times - need 15 min options

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/vassallandcoldharbour#49]
Apologies, I think there was an issue request about this but I cannot find it anywhere.

The current layout for organisations restricts opening times to be on the hour. This is not good as many close/open at the half hour and a few may want 15 min options.

If it is simple could the VAC site be tweaked to allow 15 min intervals (or if complicated, 30 min intervals) for opening and closing times. There is currently a load of content being out on the site over the next day or two and this has cropped up as an issue. Be great if we can do a quick tweak on this @pmackay

**Comment by pmackay** [comment]
Quick fix made @GilesGibson. Please check and confirm. Will leave this open to sort a more long term fix later.

**Comment by GilesGibson** [comment]
OK, looks like it is available for locations. 

Question: should we make it available for groups or do we associate groups with a location always?

**Comment by pmackay** [comment]
The intent is that groups (which are Organisations) always connect with Locations. Only locations can have opening hours, as they’re a physical place.

However you’re testing this (new) model (compared to old one) so any feedback is important! And thinking if it will work well for HH too.

-- 
Paul Mackay

On 26 October 2015 at 11:25:45, GilesGibson (notifications@github.com) wrote:

OK, looks like it is available for locations.

Question: should we make it available for groups or do we associate groups with a location always?

**Comment by GilesGibson** [comment]
Thanks for the quick fix, much appreciated.
If a bridge club meets at the library then the bridge club has "opening hours" i.e. when it is on and how long it lasts for? The library has opening hours as well. We can monitor this issue and see how it goes.

**Comment by pmackay** [comment]
That's not how I'd model it. If the bridge club meets regularly at a library, its a recurring event that has its own times.

**Comment by GilesGibson** [comment]
Fair point, lets see how it develops.

**Comment by pmackay** [comment]
Issue moved to [folklabs/openlocal #35](https://github.com/folklabs/openlocal/issues/35) via [**ZenHub**](https://www.zenhub.com/)
