### ISSUE TITLE
Location not showing on map

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/vassallandcoldharbour#50]
The new entry for the Grief Walking Service has been created. They chose Myatts Park as the location (it had been created before and used elsewhere) but it is not showing on the map display.

![image](https://cloud.githubusercontent.com/assets/6060985/10757049/036d202a-7ca0-11e5-8071-d1c3b3dfd5c0.png)

**Comment by pmackay** [comment]
Unfortunately those little widget maps are annoyingly unreliable :(

**Comment by GilesGibson** [comment]
so, can they be used or do we just hope they behave occasionally. Had a few comments from people asking why they don't appear on the map.

**Comment by GilesGibson** [comment]
Any thoughts on this? They have been asking about progress and if it can be resolved?

**Comment by GilesGibson** [comment]
They have asked again about this bug. Is it fixable easily or not?

**Comment by pmackay** [comment]
Who is asking and how urgent is it? I will try to take another look at the weekend but a fix may be quite tough.

**Comment by pmackay** [comment]
Fixed on live now - looks ok on FF, Chrome, IE. Please reply if you see issues anywhere. 

As part of this I pushed lots of updates to Drupal core and other modules, so again, raise new issues if any new strange behaviour.
